#!/usr/bin/env bash
set -euo pipefail

# Idempotent setup for:
# - ~/.jupyter/jupyter_server_config.py
# - ~/.ssh/config (Host alias + LocalForward tunnel)

HOST_ALIAS="${1:-myserver}"
SERVER_HOST="${2:-YOUR_SERVER_HOST_OR_IP}"
SERVER_USER="${3:-$USER}"
IDENTITY_FILE="${4:-$HOME/.ssh/YOUR_KEY}"
JUPYTER_PORT="${JUPYTER_PORT:-8888}"

JUPYTER_DIR="$HOME/.jupyter"
JUPYTER_CFG="$JUPYTER_DIR/jupyter_server_config.py"
SSH_DIR="$HOME/.ssh"
SSH_CFG="$SSH_DIR/config"

mkdir -p "$JUPYTER_DIR" "$SSH_DIR"
chmod 700 "$SSH_DIR"

backup_if_exists() {
  local f="$1"
  if [[ -f "$f" ]]; then
    cp "$f" "$f.bak.$(date +%Y%m%d_%H%M%S)"
  fi
}

upsert_py_setting() {
  local key="$1"
  local value="$2"
  local file="$3"

  if grep -Eq "^[[:space:]]*c\.ServerApp\.${key}[[:space:]]*=" "$file" 2>/dev/null; then
    sed -i -E "s|^[[:space:]]*c\.ServerApp\.${key}[[:space:]]*=.*$|c.ServerApp.${key} = ${value}|" "$file"
  else
    printf '\nc.ServerApp.%s = %s\n' "$key" "$value" >> "$file"
  fi
}

ensure_jupyter_config() {
  if [[ ! -f "$JUPYTER_CFG" ]]; then
    cat > "$JUPYTER_CFG" <<'PYCFG'
# Generated by setup_jupyter_ssh.sh
PYCFG
  fi

  backup_if_exists "$JUPYTER_CFG"
  upsert_py_setting "ip" '"127.0.0.1"' "$JUPYTER_CFG"
  upsert_py_setting "open_browser" "False" "$JUPYTER_CFG"
  upsert_py_setting "port" "$JUPYTER_PORT" "$JUPYTER_CFG"
  upsert_py_setting "port_retries" "10" "$JUPYTER_CFG"
}

ensure_ssh_host_block() {
  backup_if_exists "$SSH_CFG"
  touch "$SSH_CFG"
  chmod 600 "$SSH_CFG"

  local start="# >>> ${HOST_ALIAS} jupyter tunnel >>>"
  local end="# <<< ${HOST_ALIAS} jupyter tunnel <<<"

  awk -v s="$start" -v e="$end" '
    BEGIN{skip=0}
    $0==s {skip=1; next}
    $0==e {skip=0; next}
    skip==0 {print}
  ' "$SSH_CFG" > "$SSH_CFG.tmp"

  cat >> "$SSH_CFG.tmp" <<BLOCK
$start
Host $HOST_ALIAS
  HostName $SERVER_HOST
  User $SERVER_USER
  IdentityFile $IDENTITY_FILE
  ServerAliveInterval 30
  ServerAliveCountMax 3
  LocalForward $JUPYTER_PORT 127.0.0.1:$JUPYTER_PORT
$end
BLOCK

  mv "$SSH_CFG.tmp" "$SSH_CFG"
}

ensure_jupyter_config
ensure_ssh_host_block

cat <<DONE
Done.
Updated:
  - $JUPYTER_CFG
  - $SSH_CFG

Usage:
  bash setup_jupyter_ssh.sh <host_alias> <server_host_or_ip> <server_user> <identity_file>

Example:
  bash setup_jupyter_ssh.sh myserver 203.0.113.10 chuck ~/.ssh/id_ed25519
DONE
